### ISSUE TITLE
Document exporting store contents using seafuse mount

### ISSUE THREAD

**Issue by edrex** [ChatDeBlofeld/seafile-arm-docker#7]
Hi. I'm using your container image on my Odroid HC1. Thanks!

I want to use the [FUSE extension](https://manual.seafile.com/extension/fuse/) to access stored data, however being in a container complicates things. I was able to mount inside the container by adding the following to docker-compose.yml:

```
services:
  seafile:
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
 ```

Then:
```
sudo docker-compose up -d
sudo docker-compose exec seafile /bin/bash
seafile-server-latest/seaf-fuse.sh start /mnt
cp -R /mnt /shared/seafile-data/Export
```

It's rather awkward but might be worth adding to readme for others wanting to export their data.

There is also a newer FUSE client that works on a remote system over the API https://github.com/haiwen/seadrive-fuse
